version: '3.3'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: dp09udina/foodgram_backend
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    container_name: foodgram_backend

  frontend:
    image: dp09udina/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
    container_name: foodgram_frontend


  nginx:
    image: dp09udina/nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - backend
    container_name: foodgram_nginx
