# Generated by Django 3.2 on 2023-12-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'guest'), ('user', 'user'), ('admin', 'admin')], default='user', max_length=25, verbose_name='Роль'),
        ),
    ]
