# Generated by Django 3.2 on 2023-12-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='sfdsdf', max_length=150, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='sgdrgrw', max_length=156, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
